CI with Sonar
SoPra-Team-17/LibClient pull request #7
Opened 2020-04-09 17:37 UTC by csacro

2020-04-09 18:56 UTC, ottojo requested changes

2020-04-09 18:56 UTC, ottojo commented on .idea/modules.xml
> +      <module fileurl="file://$PROJECT_DIR$/.idea/LibCommon.iml" filepath="$PROJECT_DIR$/.idea/LibCommon.iml" />
LibCommon -> LibClient

2020-04-09 18:56 UTC, ottojo commented on .idea/vcs.xml
> +    <mapping directory="$PROJECT_DIR$/extern/googletest" vcs="Git" />
Invalid VCS mapping

2020-04-09 18:56 UTC, ottojo commented on .idea/deployment.xml
> +      <paths name="WSL (a6f930e1-c00b-46bf-bb10-96b77c83ce5f)">
Client specific?

2020-04-09 19:24 UTC, csacro commented on .idea/deployment.xml
> +      <paths name="WSL (a6f930e1-c00b-46bf-bb10-96b77c83ce5f)">
sieht eher nach wsl zeug aus...

2020-04-09 22:37 UTC, ottojo approved these changes

2020-04-10 16:59 UTC, Marco5de commented on .idea/LibClient.iml
> +    <option name="localAnalysisScripName" value="&lt;PROJECT&gt;" />
Klappt das lokal?

2020-04-10 17:00 UTC, Marco5de approved these changes

2020-04-10 17:17 UTC, ottojo commented on .idea/LibClient.iml
> +    <option name="localAnalysisScripName" value="&lt;PROJECT&gt;" />
habe das mal getestet, scheint nicht mehr supported zu sein.

2020-04-10 17:18 UTC, ottojo requested changes

2020-04-10 17:18 UTC, ottojo commented on .idea/LibClient.iml
> +</module>
```suggestion
<?xml version="1.0" encoding="UTF-8"?>
<module classpath="CMake" type="CPP_MODULE" version="4">
</module>
```

2020-04-10 17:20 UTC, ottojo approved these changes

2020-04-10 17:21 UTC, merged